services:
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: dev_mppi_container
    image: dev_mppi:v1.0
    volumes:
      - .:/dev_ws/python_simple_mppi
    environment:
      - UV_PROJECT_ENVIRONMENT=/uv_venv
    stdin_open: true
    tty: true